config/routes.rb
Rails.application.routes.draw do
  resources :tokimons
  resources :trainers
  root 'trainers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tokimon.rb
class Tokimon < ApplicationRecord
	belongs_to :trainer

	def calculate_total
		if(self.fly.nil?)
			self.fly = 0
		end
		if(self.fight.nil?)
			self.fight = 0
		end
		if(self.water.nil?)
			self.water = 0
		end
		if(self.electric.nil?)
			self.electric = 0
		end
		if(self.ice.nil?)
			self.ice = 0
		end
		if(self.fire.nil?)
			self.fire = 0
		end

		self.total = (self.fly + self.fight + 
		self.fire + self.water + 
		self.electric + self.ice)

		return self.total
	end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
	has_many :tokimons
end

def name
	return name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tokimons_controller.rb
class TokimonsController < ApplicationController
  before_action :set_tokimon, only: [:show, :edit, :update, :destroy]

  # GET /tokimons
  # GET /tokimons.json
  def index
    #@tokimons = Tokimon.all
    @tokimons = Tokimon.where(["name LIKE ?","%#{params[:search]}%"]).order(params[:sort])
  end

  # GET /tokimons/1
  # GET /tokimons/1.json
  def show
  end

  # GET /tokimons/new
  def new
    @tokimon = Tokimon.new
  end

  # GET /tokimons/1/edit
  def edit
  end

  # POST /tokimons
  # POST /tokimons.json
  def create
    @tokimon = Tokimon.new(tokimon_params)

    respond_to do |format|
      if @tokimon.save
        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully created.' }
        format.json { render :show, status: :created, location: @tokimon }
      else
        format.html { render :new }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokimons/1
  # PATCH/PUT /tokimons/1.json
  def update
    respond_to do |format|
      if @tokimon.update(tokimon_params)
        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully updated.' }
        format.json { render :show, status: :ok, location: @tokimon }
      else
        format.html { render :edit }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokimons/1
  # DELETE /tokimons/1.json
  def destroy
    @tokimon.destroy
    respond_to do |format|
      format.html { redirect_to tokimons_url, notice: 'Tokimon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tokimon
      @tokimon = Tokimon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tokimon_params
      params.require(:tokimon).permit(:name, :weight, :height, :fly, :fight, :fire, :water, :electric, :ice, :total, :trainer_id)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    #@trainers = Trainer.all
    @trainers = Trainer.where(["name LIKE ?","%#{params[:search]}%"])
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokimons_helper.rb
module TokimonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tokimons/_form.html.erb
<%= form_for(tokimon) do |f| %>
  <% if tokimon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tokimon.errors.count, "error") %> prohibited this tokimon from being saved:</h2>

      <ul>
      <% tokimon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div class="field">
    <%= f.label :fly %>
    <%= f.number_field :fly %>
  </div>

  <div class="field">
    <%= f.label :fight %>
    <%= f.number_field :fight %>
  </div>

  <div class="field">
    <%= f.label :fire %>
    <%= f.number_field :fire %>
  </div>

  <div class="field">
    <%= f.label :water %>
    <%= f.number_field :water %>
  </div>

  <div class="field">
    <%= f.label :electric %>
    <%= f.number_field :electric %>
  </div>

  <div class="field">
    <%= f.label :ice %>
    <%= f.number_field :ice %>
  </div>

  <!--<div class="field">
    <%= f.label :total %>
    <%= f.number_field :total %>
  </div>-->

  <!--<div class="field">
    <%= f.label :trainer_id %>
    <%= f.number_field :trainer_id %>
  </div>-->
  Trainer Name<br />
  <%= f.collection_select :trainer_id, Trainer.order(:name),:id, :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokimons/edit.html.erb
<h1>Editing Tokimon</h1>

<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Show', @tokimon %> |
<%= link_to 'Back', tokimons_path %>

app/views/tokimons/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "style.css" %>

<h1>Tokimons</h1>
<%= form_tag tokimons_path, :method => 'get' do %>
   
     <%= text_field_tag :search, params[:search] %>
     <%= submit_tag "Search", :name => nil %>
   
 <% end %>
 <br />
<table>
  <thead>
    <tr>
      <th><%= link_to "Name", :sort => "name" %></th>
      <th><%= link_to "Weight", :sort => "weight" %></th>
      <th><%= link_to "Height", :sort => "height" %></th>
      <th>Fly</th>
      <th>Fight</th>
      <th>Fire</th>
      <th>Water</th>
      <th>Electric</th>
      <th>Ice</th>
      <th>Total</th>
      <th>Trainer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokimons.each do |tokimon| %>
      <tr>
        <td><%= tokimon.name %></td>
        <td><%= tokimon.weight %></td>
        <td><%= tokimon.height %></td>
        <td><%= tokimon.fly %></td>
        <td><%= tokimon.fight %></td>
        <td><%= tokimon.fire %></td>
        <td><%= tokimon.water %></td>
        <td><%= tokimon.electric %></td>
        <td><%= tokimon.ice %></td>
        <% tokimon.calculate_total %>
        <td><%= tokimon.total %></td>
        <td><%= tokimon.trainer.name %></td>
        <td><%= link_to 'Show', tokimon %></td>
        <td><%= link_to 'Edit', edit_tokimon_path(tokimon) %></td>
        <td><%= link_to 'Destroy', tokimon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tokimon', new_tokimon_path %>
<%= link_to 'Show Trainers', trainers_path %>

app/views/tokimons/new.html.erb
<h1>New Tokimon</h1>

<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Back', tokimons_path %>

app/views/tokimons/show.html.erb
<p id="notice"><%= notice %></p>


<div id="show">
<p>
  <strong>Name:</strong>
  <%= @tokimon.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @tokimon.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @tokimon.height %>
</p>

<p>
  <strong>Fly:</strong>
  <%= @tokimon.fly %>
</p>

<p>
  <strong>Fight:</strong>
  <%= @tokimon.fight %>
</p>

<p>
  <strong>Fire:</strong>
  <%= @tokimon.fire %>
</p>

<p>
  <strong>Water:</strong>
  <%= @tokimon.water %>
</p>

<p>
  <strong>Electric:</strong>
  <%= @tokimon.electric %>
</p>

<p>
  <strong>Ice:</strong>
  <%= @tokimon.ice %>
</p>

<p>
  <strong>Total:</strong>
  
  <%= @tokimon.calculate_total %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @tokimon.trainer.name %>
</p>
</div>

<%= link_to 'Edit', edit_tokimon_path(@tokimon) %> |
<%= link_to 'Back', tokimons_path %>

app/views/trainers/_form.html.erb
<%= form_for(trainer) do |f| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <!--<div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>-->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "style.css" %>

<h1>Trainers</h1>
<%= form_tag trainers_path, :method => 'get' do %>
   
     <%= text_field_tag :search, params[:search] %>
     <%= submit_tag "Search", :name => nil %>
   
 <% end %>
 <br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= link_to 'Show Tokimons & Level', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>
<%= link_to 'Show Tokimons', tokimons_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>
<% @tnum = 0 %>
<% @trainer.tokimons.each do |tokimon| %>
<% @tnum += 1 %>
<% end %>
<p>
  <strong>Level:</strong>
  <%= (@tnum/3) %>
</p>

<h3>Tokimon</h3>
<table>
<tr> 
    <th>Name</th>  
    <th>Weight</th>  
    <th>Height</th> 
    <th>Fly</th> 
    <th>Fight</th> 
    <th>Fire</th> 
    <th>Water</th> 
    <th>Electric</th> 
    <th>Ice</th> 
    <th>Total</th> 
</tr>

<% @trainer.tokimons.each do |tokimon| %>
<tr>
    <td><%= tokimon.name %></td>
    <td><%= tokimon.weight %></td>
    <td><%= tokimon.height %></td>
    <td><%= tokimon.fly %></td>
    <td><%= tokimon.fight %></td>
    <td><%= tokimon.fire %></td>
    <td><%= tokimon.water %></td>
    <td><%= tokimon.electric %></td>
    <td><%= tokimon.ice %></td>
    <% tokimon.calculate_total %>
    <td><%= tokimon.total %></td>
</tr>
<% end %>
</table>  

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>